# -*- coding: utf-8 -*-
"""polynomial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_J2k6NPxjG7i3k6RoaDojqBIpkFzfb_d
"""

import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv("/content/household_energy_consumption.csv")

df.head()

df.info()

df.describe()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

df.shape

df.columns

df.isnull().sum()

x=df[["Household_Size","Avg_Temperature_C","Peak_Hours_Usage_kWh"]]
y=df["Energy_Consumption_kWh"]

X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=42)

from numpy import polynomial
poly=PolynomialFeatures(degree=2)
X_train_poly=poly.fit_transform(X_train)
X_test_poly=poly.transform(X_test)

model=LinearRegression()
model.fit(X_train_poly,Y_train)

Y_pred=model.predict(X_test_poly)

mae=mean_absolute_error(Y_test,Y_pred)
mse=mean_squared_error(Y_test,Y_pred)
rmse=mse**0.5
r2=r2_score(Y_test,Y_pred)

print("\nModel Evaluation")
print("-----------------")
print("MAE:",mae)
print("MSE:",mse)
print("RMSE:",rmse)
print("R-squared:",r2)

plt.figure(figsize=(10, 6))
plt.scatter(Y_test, Y_pred)
plt.xlabel("Actual Energy Consumption (KWh)")
plt.ylabel("Predicted Energy Consumption (KWh)")
plt.title("Actual vs Predicted Energy Consumption")
plt.show()

